// Traducciones de las pantallas de alarmas, diálogos y registro (se mantienen aparte para trabajar en paralelo).
// Clave = texto en español tal como aparece en tr('...'); {x} son marcadores que se reemplazan.
const Map<String, Map<String, String>> traduccionesExtra = {'en': {
  // Registro
  'Crear Cuenta': 'Create account',
  'Español': 'Spanish',
  'English': 'English',
  'Hñähñu': 'Hñähñu',
  'Registro en MEDMAP': 'Sign up for MEDMAP',
  'Selecciona tu tipo de usuario para configurar tu cuenta.': 'Choose your user type to set up your account.',
  'Tipo de usuario': 'User type',
  'Usuario': 'User',
  'Cuidador': 'Caregiver',
  'Médico': 'Doctor',
  'Cédula profesional': 'Professional license',
  'Clínica o Institución médica': 'Clinic or medical institution',
  'Validaremos tu cédula. Mientras tanto tu perfil mostrará "Cédula en revisión".':
      'We will verify your license. Meanwhile your profile will show "License under review".',
  '¿Requieres apoyo de accesibilidad?': 'Do you need accessibility support?',
  'Activa letra grande, alto contraste y lecturas con audio.': 'Turns on large text, high contrast and audio reading.',
  'Error: {e}': 'Error: {e}',
  'Completar Registro': 'Complete sign-up',
  'La contraseña debe tener al menos 8 caracteres.': 'The password must have at least 8 characters.',
  '¡Registro exitoso! Por favor inicia sesión.': 'Sign-up successful! Please log in.',
  'Error al registrar la cuenta': 'Could not create the account',
  '¿Ya tienes cuenta? Inicia sesión': 'Already have an account? Log in',
  'La cédula profesional debe tener 7 u 8 dígitos.': 'The professional license must have 7 or 8 digits.',
  'Escribe tu clínica o institución médica.': 'Enter your clinic or medical institution.',
  'Escanea el QR de un paciente que te tenga asignado como cuidador.': 'Scan the QR of a patient who has you assigned as caregiver.',
  'QR del paciente': 'Patient QR',
  'Escanea el código QR que aparece en la app del paciente.': 'Scan the QR code shown in the patient\'s app.',
  'Paciente a tu cargo': 'Patient in your care',
  'Escanea el QR del paciente. Solo puedes registrarte si el equipo de salud ya te asignó como su cuidador.':
      'Scan the patient\'s QR. You can only sign up if the health team already assigned you as their caregiver.',
  'Escanear QR del paciente': 'Scan patient QR',
  'Paciente: {p}': 'Patient: {p}',
  'Cuidador asignado: {nombre}. Te registrarás como su cuidador.': 'Assigned caregiver: {nombre}. You will sign up as their caregiver.',
  'Este paciente aún no tiene un cuidador asignado. Pide al equipo de salud que te registre como su cuidador para continuar.':
      'This patient has no assigned caregiver yet. Ask the health team to register you as their caregiver to continue.',
  'Escanear otro QR': 'Scan another QR',

  // Lector QR
  'Apunta la cámara al código QR del paciente.': 'Point the camera at the patient\'s QR code.',
  'Sin conexión. Revisa tu internet e intenta de nuevo.': 'No connection. Check your internet and try again.',
  'Código no válido o paciente no encontrado.': 'Invalid code or patient not found.',
  'No se pudo abrir la cámara. Usa "Escribir código".': 'Could not open the camera. Use "Type code".',
  'Escribir código': 'Type code',
  'Código del paciente': 'Patient code',
  'Código que aparece bajo el QR': 'Code shown under the QR',

  // Diálogos
  'Confirmar': 'Confirm',
  'Cancelar': 'Cancel',
  'Continuar': 'Continue',

  // Perfil
  'Escribe tu nombre.': 'Enter your name.',
  'Escribe un correo válido.': 'Enter a valid email.',
  'Completa fecha de nacimiento, sexo y programa de cuidado.': 'Complete date of birth, sex and care program.',
  'Nombre completo': 'Full name',
  'Correo electrónico': 'Email',
  'Teléfono': 'Phone',
  'Fecha de nacimiento': 'Date of birth',
  'Elegir fecha': 'Choose date',
  'Sexo': 'Sex',
  'Mujer': 'Female',
  'Hombre': 'Male',
  'Tipo de sangre': 'Blood type',
  'No sé': 'I don\'t know',
  'Alergias a medicamentos': 'Drug allergies',
  'Programa de seguimiento (elige uno o más)': 'Follow-up program (choose one or more)',
  'Embarazo y puerperio': 'Pregnancy and postpartum',
  'Crónico-degenerativas': 'Chronic diseases',
  'Adulto mayor': 'Older adult',
  '¿En qué etapa te encuentras?': 'Which stage are you in?',
  'Embarazo': 'Pregnancy',
  'Puerperio (postparto - primeros 42 días)': 'Puerperium (postpartum - first 42 days)',
  'Agregar alergia': 'Add allergy',
  'Puedes agregar varias. ¿No está? Elige "Otro medicamento…".': 'You can add several. Not listed? Choose "Other medication…".',
  'Otro medicamento…': 'Other medication…',
  'Sin alergias registradas. Déjalo vacío si no tienes alergias a medicamentos.':
      'No allergies recorded. Leave it empty if you have no drug allergies.',
  'Quitar {a}': 'Remove {a}',
  'Otro medicamento': 'Other medication',
  'Nombre del medicamento': 'Medication name',
  'Agregar': 'Add',

  // Foto de perfil
  'Cambiar foto de perfil': 'Change profile photo',
  'Tomar foto': 'Take photo',
  'Elegir imagen': 'Choose image',
  'Elegir de la galería': 'Choose from gallery',
  'Quitar foto': 'Remove photo',
  'Foto eliminada.': 'Photo removed.',
  'Foto de perfil actualizada.': 'Profile photo updated.',
  'Sin conexión. La foto no se guardó.': 'No connection. The photo was not saved.',
  'No se pudo cambiar la foto.': 'Could not change the photo.',
  'Médico verificado': 'Verified doctor',
  'Cédula en revisión': 'License under review',
  'Cédula profesional validada': 'Professional license verified',
  'Tu cédula profesional se está verificando': 'Your professional license is being verified',

  // Alarma y tomas
  'Ya la tomé': 'I took it',
  'Más tarde': 'Later',
  'Recordatorios de toma': 'Dose reminders',
  'Alarma de medicamentos': 'Medication alarm',
  'Suena y vibra a la hora de cada toma hasta que respondas.': 'Rings and vibrates at each dose time until you respond.',
  'Hora de tu medicamento': 'Time for your medication',
  '{med} · {dosis} · {hora}': '{med} · {dosis} · {hora}',
  'Toma omitida de las {hora}': 'Missed dose at {hora}',
  'Te toca a las {hora}': 'Due at {hora}',
  'Es hora de tomar {med}': 'It is time to take {med}',
  '¿Ya tomaste {med}?': 'Did you take {med}?',
  'Se registrará la toma de las {hora}.': 'The {hora} dose will be recorded.',
  'Toma registrada.': 'Dose recorded.',
  'Te lo recordaremos en {n} minutos.': 'We will remind you in {n} minutes.',
  'No se pudo registrar. Intenta de nuevo.': 'Could not record it. Try again.',
  'Sin conexión: guardado en el teléfono. Se enviará solo.': 'No connection: saved on the phone. It will be sent automatically.',
  'Toma de medicamento': 'Medication dose',
  '¡Es hora de tu medicamento!': 'It is time for your medication!',
  'Dosis': 'Dose',
  'Horario': 'Time',
  'Vía': 'Route',
  'oral': 'oral',
  'Estado: {estado}': 'Status: {estado}',
  'Pendiente': 'Pending',
  'Tomada': 'Taken',
  'Omitida': 'Missed',
  'Pospuesta': 'Snoozed',
  'Pasaron 30 minutos sin respuesta y la toma quedó como omitida.': '30 minutes passed without a response and the dose was marked as missed.',
  '¿En cuánto tiempo te lo recordamos?': 'When should we remind you?',
  'En {n} minutos': 'In {n} minutes',
  'Hoy': 'Today',
  'Próximas tomas': 'Upcoming doses',
  '{hora} · {med}': '{hora} · {med}',
  '{dosis} · {estado}': '{dosis} · {estado}',
  'Mostrar mi código QR': 'Show my QR code',
  // Diagnóstico de conexión (pantalla de desarrollo)
  'Diagnóstico de conexión': 'Connection diagnostics',
  'Modo demo: se prueba contra los datos de demostración, no contra el servidor.': 'Demo mode: the test uses the demo data, not the server.',
  'Modo servidor: se prueba con tu sesión actual.': 'Server mode: the test uses your current session.',
  'Solo hace consultas de lectura. El reporte describe la forma de cada respuesta (tipos y campos), sin datos personales, sin el token y sin la dirección del servidor.':
      'Only read requests are made. The report describes the shape of each response (types and fields), without personal data, the token or the server address.',
  'Inicia sesión para probar la conexión.': 'Sign in to test the connection.',
  'Probar conexión': 'Test connection',
  'Copiar reporte': 'Copy report',
  'Progreso de la prueba': 'Test progress',
  'Probando… {n} de {t}': 'Testing… {n} of {t}',
  '{ok} correctas · {err} con error · {om} omitidas': '{ok} passed · {err} failed · {om} skipped',
  'Prueba omitida': 'Test skipped',
  'Prueba correcta': 'Test passed',
  'Prueba con error': 'Test failed',
  'Se omitió: {m}': 'Skipped: {m}',
  'Código de error: {c}': 'Error code: {c}',
  'Sin respuesta ({t})': 'No response ({t})',
  'Forma de la respuesta': 'Response shape',
  'El adaptador no produjo datos.': 'The adapter produced no data.',
  'Reporte copiado': 'Report copied',
  'solo para el equipo de salud': 'health team only',
  'no aplica al equipo de salud': 'does not apply to the health team',
  'no aplica al paciente': 'does not apply to the patient',
  'sin paciente activo': 'no active patient',
  // Validación de credenciales, formularios y mediciones
  'Escribe tu correo.': 'Enter your email.',
  'Escribe un correo válido, por ejemplo nombre@correo.com.': 'Enter a valid email, for example name@email.com.',
  'La contraseña no puede tener más de 72 caracteres.': 'The password cannot be longer than 72 characters.',
  'La contraseña debe combinar letras y números.': 'The password must combine letters and numbers.',
  'tu nombre': 'your name',
  'Escribe {campo}.': 'Enter {campo}.',
  'El nombre es demasiado largo.': 'The name is too long.',
  'El nombre solo puede llevar letras y espacios.': 'The name can only contain letters and spaces.',
  'Escribe nombre y apellido.': 'Enter first and last name.',
  'Escribe un teléfono.': 'Enter a phone number.',
  'El teléfono debe tener 10 dígitos.': 'The phone number must have 10 digits.',
  'Revisa el teléfono: no parece real.': 'Check the phone number: it does not look real.',
  'Elige la fecha de nacimiento.': 'Choose the date of birth.',
  'La fecha de nacimiento no puede ser futura.': 'The date of birth cannot be in the future.',
  'Revisa la fecha de nacimiento: la edad pasa de 120 años.': 'Check the date of birth: the age is over 120 years.',
  'El programa de embarazo y puerperio solo aplica a mujeres.': 'The pregnancy and postpartum program only applies to women.',
  'Revisa la fecha de nacimiento: la edad no corresponde a un embarazo.': 'Check the date of birth: the age does not match a pregnancy.',
  'El programa de adulto mayor es para personas de 60 años o más.': 'The older adult program is for people aged 60 or over.',
  'El número no puede ser negativo.': 'The number cannot be negative.',
  'Escribe un número entero, sin decimales.': 'Enter a whole number, without decimals.',
  'Revisa el número: debe estar entre {min} y {max}.': 'Check the number: it must be between {min} and {max}.',
  'Ocultar contraseña': 'Hide password',
  'Mostrar contraseña': 'Show password',
  'Elige el sexo.': 'Choose the sex.',
  'Teléfono (10 dígitos, opcional)': 'Phone (10 digits, optional)',
  'Escribe tu contraseña.': 'Enter your password.',
  'No se pudo iniciar sesión. Intenta de nuevo.': 'Could not sign in. Try again.',
  'Mínimo 8 caracteres, con letras y números.': 'At least 8 characters, with letters and numbers.',
  'Repite la contraseña': 'Repeat the password',
  '7 u 8 dígitos, como aparece en el Registro Nacional de Profesionistas.': '7 or 8 digits, as shown in the National Registry of Professionals.',
  'Las contraseñas no coinciden.': 'The passwords do not match.',
  'Cuenta creada. Tu cédula quedará en revisión. Inicia sesión.': 'Account created. Your license will be reviewed. Sign in.',
  'Sin conexión. El registro necesita internet.': 'No connection. Sign-up needs internet.',
  'El registro en línea aún no está disponible. Pide tu cuenta a tu clínica.': 'Online sign-up is not available yet. Ask your clinic for an account.',
  'Ya existe una cuenta con ese correo. Inicia sesión o recupera tu contraseña.': 'An account with that email already exists. Sign in or recover your password.',
  'el nombre del paciente': 'the patient’s name',
  'el nombre del cuidador': 'the caregiver’s name',
  'No se pudo obtener la versión del aviso de privacidad. Revisa la conexión e intenta de nuevo.': 'Could not get the privacy notice version. Check the connection and try again.',
  'Teléfono del cuidador (10 dígitos, opcional)': 'Caregiver’s phone (10 digits, optional)',
  'Para que el equipo de salud pueda localizarlo.': 'So the health team can reach them.',
  '¿Es correcto {v} {u}?': 'Is {v} {u} correct?',
  'Es un valor poco común. Revisa que lo escribiste igual que en el aparato.': 'This is an unusual value. Check that you typed it exactly as the device shows.',
  'Sí, es correcto': 'Yes, it’s correct',
  'Corregir': 'Correct it',
  'Elige la lectura correcta donde hay dos opciones.': 'Choose the correct reading where there are two options.',
  'Agrega al menos un horario a cada medicamento.': 'Add at least one time to each medicine.',
  'Revisa los datos e intenta de nuevo.': 'Check the data and try again.',
  'Revisa: {campos}.': 'Check: {campos}.',
  'Cédula profesional registrada por tu clínica': 'Professional license registered by your clinic',
  'correo': 'email',
  'contraseña': 'password',
  'nombre': 'name',
  'teléfono': 'phone',
  'fecha de nacimiento': 'date of birth',
  'sexo': 'sex',
  'tipo de sangre': 'blood type',
  'alergias': 'allergies',
  'programa de cuidado': 'care program',
  'cuidador': 'caregiver',
  'consentimiento': 'consent',
  'cédula profesional': 'professional license',
  'valor': 'value',
  'segundo valor': 'second value',
  'respuesta': 'answer',
  'hora de la medición': 'measurement time',
  'registros': 'records',
  'tomas': 'doses',
  'dosis': 'dose',
  'frecuencia': 'frequency',
  'horarios': 'times',
  'medicamentos': 'medicines',
  'foto': 'photo',
  'texto de la receta': 'prescription text',
  'tipo': 'type',
  'zona del cuerpo': 'body area',
  'lado': 'side',
  'descripción': 'description',
}};
