// Diccionario de textos de pantalla. Clave: texto en español tal como aparece en tr('...').
// Para agregar un idioma: añade otro mapa (p. ej. 'ote': {...}) con las mismas claves.
const Map<String, Map<String, String>> traducciones = {'en': _en};

const _en = <String, String>{
  // Navegación y títulos
  'Hoy': 'Today', 'Registrar': 'Log', 'Medicamentos': 'Medications', 'Historial': 'History', 'Perfil': 'Profile',
  'Alertas': 'Alerts', 'Pacientes': 'Patients', 'Escanear QR': 'Scan QR', 'Notificaciones': 'Notifications',
  'Preferencias': 'Preferences', 'Preferencias y accesibilidad': 'Preferences and accessibility', 'Expediente': 'Medical record',
  'Plan de control': 'Monitoring plan', 'Ver expediente': 'View medical record', 'Alta de paciente': 'Register patient',
  'Mis pacientes': 'My patients', 'Mis medicamentos': 'My medications', 'Detalle de alerta': 'Alert details',
  'Atender alerta': 'Handle alert', 'Resultado': 'Result', 'Sincronización': 'Sync', 'Toma de medicamento': 'Medication dose',
  'Editar perfil': 'Edit profile', 'Paciente': 'Patient', 'Paciente {id}': 'Patient {id}', 'Cuidador': 'Caregiver',
  'Equipo de salud': 'Health team', 'Médico': 'Doctor', 'Usuario': 'Patient', 'Recordatorio': 'Reminder',
  'Recordatorios': 'Reminders', 'Recordatorios de toma': 'Dose reminders', 'Alerta': 'Alert',

  // Inicio de sesión y registro
  'Iniciar sesión': 'Sign in', 'Cerrar sesión': 'Sign out', '¿Cerrar sesión?': 'Sign out?',
  'Tendrás que iniciar sesión otra vez.': 'You will need to sign in again.', 'Correo': 'Email',
  'Correo electrónico': 'Email', 'Correo o contraseña incorrectos': 'Incorrect email or password',
  'Modo demo: entrar sin login': 'Demo mode: enter without signing in', 'Entrar como {rol}': 'Enter as {rol}',
  'Probar Pantalla de Registro': 'Try the sign-up screen', 'Crear Cuenta': 'Create account', 'Registro en SENDA': 'Sign up for SENDA',
  'Selecciona tu tipo de usuario para configurar tu cuenta.': 'Choose your user type to set up your account.',
  'Tipo de usuario': 'User type', 'Completar Registro': 'Complete sign-up', '¿Ya tienes cuenta? Inicia sesión': 'Already have an account? Sign in',
  '¡Registro exitoso! Por favor inicia sesión.': 'Sign-up complete! Please sign in.', 'Error al registrar la cuenta': 'Could not create the account',
  'Error: {e}': 'Error: {e}', 'La contraseña debe tener al menos 8 caracteres.': 'The password must have at least 8 characters.',
  'Escribe tu nombre.': 'Enter your name.', 'Escribe un correo válido.': 'Enter a valid email.',
  'Escribe tu nombre completo': 'Enter your full name', 'Nombre completo': 'Full name', 'Teléfono': 'Phone',
  'Teléfono o contacto': 'Phone or contact', 'Activa la biometría en tu perfil e inicia sesión con tu contraseña una vez.':
      'Turn on biometrics in your profile and sign in with your password once.',
  'Entrar con biometría': 'Sign in with biometrics', 'Pide tu huella o rostro al abrir la app.': 'Asks for your fingerprint or face when opening the app.',
  'No disponible en este dispositivo.': 'Not available on this device.', 'Tu sesión expiró': 'Your session expired',
  'Tu sesión expiró. Inicia sesión de nuevo.': 'Your session expired. Sign in again.', 'Inicia sesión otra vez para continuar.': 'Sign in again to continue.',
  'Cédula profesional': 'Professional license number', 'Clínica o Institución médica': 'Clinic or medical institution',
  'Clínica o institución': 'Clinic or institution', 'Escribe tu clínica o institución médica.': 'Enter your clinic or medical institution.',
  'La cédula profesional debe tener 7 u 8 dígitos.': 'The professional license number must have 7 or 8 digits.',
  'Validaremos tu cédula. Mientras tanto tu perfil mostrará "Cédula en revisión".':
      'We will verify your license. Meanwhile your profile will show "License under review".',
  'Médico verificado': 'Verified doctor', 'Cédula en revisión': 'License under review',
  'Cédula profesional validada': 'Professional license verified', 'Tu cédula profesional se está verificando': 'Your professional license is being verified',
  'Paciente a tu cargo': 'Patient in your care', 'Escanear QR del paciente': "Scan the patient's QR",
  'Escanea el QR del paciente. Solo puedes registrarte si el equipo de salud ya te asignó como su cuidador.':
      "Scan the patient's QR. You can only sign up if the health team already assigned you as their caregiver.",
  'Escanea el QR de un paciente que te tenga asignado como cuidador.': 'Scan the QR of a patient who has you assigned as caregiver.',
  'Escanea el código QR que aparece en la app del paciente.': "Scan the QR code shown in the patient's app.",
  'Escanear otro QR': 'Scan another QR', 'Paciente: {p}': 'Patient: {p}',
  'Cuidador asignado: {nombre}. Te registrarás como su cuidador.': 'Assigned caregiver: {nombre}. You will sign up as their caregiver.',
  'Este paciente aún no tiene un cuidador asignado. Pide al equipo de salud que te registre como su cuidador para continuar.':
      'This patient has no assigned caregiver yet. Ask the health team to register you as their caregiver to continue.',
  'QR del paciente': "Patient's QR", '¿Requieres apoyo de accesibilidad?': 'Do you need accessibility support?',
  'Activa letra grande, alto contraste y lecturas con audio.': 'Turns on large text, high contrast and audio reading.',

  // Privacidad y consentimiento
  'Privacidad y consentimiento': 'Privacy and consent', 'Aviso de privacidad': 'Privacy notice', 'Consentimiento informado': 'Informed consent',
  'He leído el aviso de privacidad': 'I have read the privacy notice', 'Acepto el seguimiento de mi salud en esta app': 'I accept health monitoring in this app',
  'Aceptar y continuar': 'Accept and continue', 'No acepto': 'I do not accept', 'Tu firma': 'Your signature',
  'Firma del paciente o su representante': "Signature of the patient or their representative",

  // Perfil
  'Cambiar foto de perfil': 'Change profile photo', 'Tomar foto': 'Take photo', 'Elegir de la galería': 'Choose from gallery',
  'Elegir imagen': 'Choose image', 'Quitar foto': 'Remove photo', 'Foto de perfil actualizada.': 'Profile photo updated.',
  'Foto eliminada.': 'Photo removed.', 'No se pudo cambiar la foto.': 'Could not change the photo.',
  'Sin conexión. La foto no se guardó.': 'No connection. The photo was not saved.', 'Perfil actualizado.': 'Profile updated.',
  'Guardar cambios': 'Save changes', 'Mi código QR': 'My QR code', 'Mostrar mi código QR': 'Show my QR code',
  'Muestra este código en la clínica para identificarte en consulta': 'Show this code at the clinic to identify yourself',
  'Código QR de identificación': 'Identification QR code', 'Código QR de identificación del paciente': "Patient's identification QR code",
  'Entrega este código al paciente para identificarlo en consulta.': 'Give this code to the patient to identify them at appointments.',
  'Fecha de nacimiento': 'Date of birth', 'Elegir fecha': 'Choose date', 'Sexo': 'Sex', 'Mujer': 'Female', 'Hombre': 'Male',
  'Tipo de sangre': 'Blood type', 'No sé': "I don't know", 'Alergias (opcional)': 'Allergies (optional)',
  'Alergias a medicamentos': 'Drug allergies', 'Ninguna registrada': 'None recorded', 'Agregar alergia': 'Add allergy',
  'Otro medicamento…': 'Other medication…', 'Otro medicamento': 'Other medication', 'Nombre del medicamento': 'Medication name',
  'Agregar': 'Add', 'Quitar {a}': 'Remove {a}',
  'Puedes agregar varias. ¿No está? Elige "Otro medicamento…".': 'You can add several. Not listed? Choose "Other medication…".',
  'Sin alergias registradas. Déjalo vacío si no tienes alergias a medicamentos.': 'No allergies recorded. Leave it empty if you have no drug allergies.',
  'Programa de cuidado': 'Care program', 'Programa de seguimiento (elige uno o más)': 'Follow-up program (choose one or more)',
  'Embarazo y puerperio': 'Pregnancy and postpartum', 'Crónico-degenerativas': 'Chronic diseases', 'Adulto mayor': 'Older adult',
  '¿En qué etapa te encuentras?': 'Which stage are you in?', 'Embarazo': 'Pregnancy', 'Puerperio': 'Postpartum',
  'Puerperio (postparto - primeros 42 días)': 'Postpartum (first 42 days)',
  'Completa fecha de nacimiento, sexo y programa de cuidado.': 'Complete date of birth, sex and care program.',
  '{n} años': '{n} years old',

  // Preferencias
  'Idioma': 'Language', 'Español': 'Spanish', 'English': 'English', 'Hñähñu': 'Hñähñu', 'Otomí del Mezquital (ote)': 'Mezquital Otomi (ote)',
  'Alto contraste': 'High contrast', 'Botones grandes': 'Large buttons', 'Letra grande y botones grandes': 'Large text and large buttons',
  'Prefiero escuchar audios': 'I prefer listening to audio', 'Prefiero pictogramas': 'I prefer pictograms',
  'Prefiere escuchar audios': 'Prefers listening to audio', 'Prefiere pictogramas': 'Prefers pictograms',
  'Tamaño de letra: {n}%': 'Text size: {n}%', 'Variante': 'Variant',
  'Se muestran texto, audio y pictograma cuando existen en el catálogo.': 'Text, audio and pictogram are shown when available in the catalog.',
  'Simular sin conexión (demo)': 'Simulate offline (demo)',

  // Hoy, medicamentos y tomas
  'Próximas tomas': 'Upcoming doses', 'Hora de tu medicamento': 'Time for your medication', 'Ya la tomé': 'I took it',
  'Más tarde': 'Later', 'Pendiente': 'Pending', 'Tomada': 'Taken', 'Omitida': 'Missed', 'Pospuesta': 'Snoozed',
  'Toma registrada.': 'Dose recorded.', 'Toma omitida': 'Missed dose', 'Dosis': 'Dose', 'Horario': 'Time', 'Horarios': 'Times', 'Vía': 'Route',
  'Pasaron 30 minutos sin respuesta y la toma quedó como omitida.': '30 minutes passed without a response and the dose was marked as missed.',
  'Aún no tienes medicamentos': "You don't have medications yet", 'Toma una foto de tu receta o caja para agregarlos.': 'Take a photo of your prescription or box to add them.',
  'Escuchar indicaciones': 'Listen to instructions', 'Detener audio': 'Stop audio', 'Detener': 'Stop',
  'Alarma de medicamentos': 'Medication alarm', 'Suena y vibra a la hora de cada toma hasta que respondas.': 'Rings and vibrates at each dose time until you respond.',
  '{med} · {dosis} · {hora}': '{med} · {dosis} · {hora}',

  // Receta
  'Escanear receta o caja': 'Scan prescription or box', 'Foto de la receta': 'Prescription photo', 'Leyendo la receta': 'Reading the prescription',
  'Lo que se detectó': 'What was detected', 'Revisa y corrige': 'Review and correct', 'Horarios de toma': 'Dose times', 'Confirmar': 'Confirm',
  'Listo': 'Done', 'Toma una foto clara de la receta o de la caja del medicamento.': 'Take a clear photo of the prescription or the medication box.',
  'Tomar otra foto': 'Take another photo', 'Foto lista': 'Photo ready', 'Analizar receta': 'Analyze prescription',
  'Leyendo tu receta… puede tardar unos segundos.': 'Reading your prescription… it may take a few seconds.',
  'Un sistema automático leyó la receta y puede equivocarse. No se guarda nada hasta que tú confirmes.':
      'An automatic system read the prescription and may make mistakes. Nothing is saved until you confirm.',
  'Se detectaron {n} medicamento(s).': '{n} medication(s) detected.', 'Texto leído': 'Text read',
  'Detectado automáticamente · revísalo': 'Detected automatically · please review', 'Revisar medicamentos': 'Review medications',
  'No detectamos medicamentos': "We didn't detect medications", 'Prueba con una foto más clara y con buena luz.': 'Try a clearer photo with good lighting.',
  'No se pudo leer la receta. Prueba con otra foto.': "Couldn't read the prescription. Try another photo.",
  'Sin conexión. Para leer la receta necesitas internet.': 'No connection. You need internet to read the prescription.',
  'Nombre comercial': 'Brand name', 'Sustancia activa': 'Active ingredient', 'Concentración': 'Strength', 'Frecuencia': 'Frequency',
  'Descartar este medicamento': 'Discard this medication', 'No queda ningún medicamento.': 'No medications left.',
  'Completa nombre y dosis de cada medicamento.': 'Complete name and dose for each medication.',
  'Estos son los horarios propuestos. Cámbialos si hace falta; a esas horas sonará un recordatorio en tu teléfono.':
      'These are the suggested times. Change them if needed; a reminder will ring on your phone at those times.',
  'Agregar horario': 'Add time', 'Cambiar horario {h}': 'Change time {h}', 'Quitar horario {h}': 'Remove time {h}',
  'Sin horarios. Agrega al menos uno.': 'No times. Add at least one.', 'Revisa que todo sea correcto:': 'Check that everything is correct:',
  'Solo se guardará lo que revisaste. Se programarán recordatorios en tu teléfono.': 'Only what you reviewed will be saved. Reminders will be scheduled on your phone.',
  'Confirmar y guardar': 'Confirm and save', '¿Guardar estos medicamentos?': 'Save these medications?', 'Medicamentos guardados': 'Medications saved',
  'Los recordatorios quedaron programados en tu teléfono.': 'The reminders were scheduled on your phone.',
  'No se pudieron programar los recordatorios. Revisa el permiso de notificaciones.': "Couldn't schedule the reminders. Check the notification permission.",
  'Toma {dosis}': 'Take {dosis}', 'Sin conexión. No se guardó nada; intenta de nuevo.': 'No connection. Nothing was saved; try again.',

  // Registro de mediciones e historial
  'Registro de mediciones': 'Measurement log', 'Presión': 'Blood pressure', 'Glucosa': 'Glucose', 'Día': 'Day', 'Semana': 'Week', 'Mes': 'Month',
  'día': 'day', 'semana': 'week', 'mes': 'month', 'Últimos 14 días': 'Last 14 days', 'Últimas 12 semanas': 'Last 12 weeks',
  'Últimos 6 meses': 'Last 6 months', 'Promedio': 'Average', 'Mediciones': 'Measurements', 'Medición': 'Measurement',
  'medición': 'measurement', 'mediciones': 'measurements', 'En meta': 'On target', 'Meta': 'Target', 'Menor a {s}/{d}': 'Below {s}/{d}',
  'Estable respecto a {ref}': 'Stable compared with {ref}', 'Bajó {d} {u} respecto a {ref}': 'Down {d} {u} compared with {ref}',
  'Subió {d} {u} respecto a {ref}': 'Up {d} {u} compared with {ref}', 'Bajó {n} {u}': 'Down {n} {u}',
  'la semana anterior': 'the previous week', 'las 6 semanas anteriores': 'the previous 6 weeks', 'los 3 meses anteriores': 'the previous 3 months',
  '{txt} (sistólica)': '{txt} (systolic)', 'Tendencia': 'Trend', 'Promedio de presión por {u}': 'Average blood pressure per {u}',
  'Promedio de glucosa por {u}': 'Average glucose per {u}', 'Frecuencia de mediciones': 'Measurement frequency',
  'Cuántas veces te mediste por {u}': 'How many times you measured per {u}', 'Cuántas veces se midió por {u}': 'How many times they measured per {u}',
  'Sistólica': 'Systolic', 'Diastólica': 'Diastolic', 'Límite de meta': 'Target limit', 'Rango de meta': 'Target range',
  'Todas las mediciones': 'All measurements', 'Ver más': 'Show more', 'Historial de mediciones': 'Measurement history',
  'Aún no hay mediciones de presión.': 'No blood pressure measurements yet.', 'Aún no hay mediciones de glucosa.': 'No glucose measurements yet.',
  'Gráfica de presión. Último promedio: {s} sobre {d}.': 'Blood pressure chart. Latest average: {s} over {d}.',
  'Gráfica de glucosa. Último promedio: {g} mg/dL.': 'Glucose chart. Latest average: {g} mg/dL.',
  'Gráfica de frecuencia: {n} mediciones, en promedio {p} por {u}.': 'Frequency chart: {n} measurements, on average {p} per {u}.',
  'sin datos': 'no data', 'Valor': 'Value', 'Fecha': 'Date', 'Hora': 'Time',
  'mín / máx / frecuencia / meta → PUT /pacientes/:id/plan': 'min / max / frequency / target → PUT /pacientes/:id/plan',
  'Lun': 'Mon', 'Mar': 'Tue', 'Mié': 'Wed', 'Jue': 'Thu', 'Vie': 'Fri', 'Sáb': 'Sat', 'Dom': 'Sun',
  'ene': 'Jan', 'feb': 'Feb', 'mar': 'Mar', 'abr': 'Apr', 'may': 'May', 'jun': 'Jun', 'jul': 'Jul', 'ago': 'Aug', 'sep': 'Sep',
  'oct': 'Oct', 'nov': 'Nov', 'dic': 'Dec',

  // Alertas y notificaciones
  'Sin alertas activas': 'No active alerts', 'Cuando haya una alerta la verás aquí.': 'When there is an alert you will see it here.',
  'Gravedad': 'Severity', 'Motivo': 'Reason', 'Registro que la originó': 'Record that triggered it', 'Sin registro asociado.': 'No associated record.',
  'Acción tomada (obligatoria)': 'Action taken (required)', 'Describe la acción': 'Describe the action', '¿Marcar como atendida?': 'Mark as handled?',
  'Se guardará: "{a}"': 'This will be saved: "{a}"', 'Alerta atendida.': 'Alert handled.',
  'Sin conexión. No se pudo atender la alerta.': 'No connection. The alert could not be handled.',
  'Se administró medicamento indicado': 'The prescribed medication was given', 'Se acudió a urgencias': 'Went to the emergency room',
  'Se contactó al paciente': 'The patient was contacted', 'Todas': 'All', 'No leídas': 'Unread', 'Omitidas': 'Missed', 'Nueva': 'New',
  'Marcar todas': 'Mark all', 'Sin notificaciones': 'No notifications', 'Aquí verás recordatorios, alertas y tomas omitidas.':
      'Here you will see reminders, alerts and missed doses.', 'No hay notificaciones en este filtro.': 'No notifications in this filter.',
  'Notificaciones, {n} sin leer': 'Notifications, {n} unread', 'Sin leer. ': 'Unread. ', 'Nada por aquí': 'Nothing here',

  // Equipo de salud
  'Aún no hay pacientes': 'No patients yet', 'Da de alta al primero con el botón de abajo.': 'Register the first one with the button below.',
  'Datos del paciente': 'Patient details', 'Cuidador responsable': 'Responsible caregiver', 'Nombre del cuidador': "Caregiver's name",
  'QR de identificación': 'Identification QR', 'Diagnósticos (opcional)': 'Diagnoses (optional)', 'Firmar y dar de alta': 'Sign and register',
  'Completa nombre, fecha de nacimiento y sexo.': 'Complete name, date of birth and sex.', 'Elige al menos un programa de cuidado.': 'Choose at least one care program.',
  'Escribe el nombre del cuidador responsable.': "Enter the responsible caregiver's name.", 'Sin conexión. El alta necesita internet.': 'No connection. Registration needs internet.',
  'No se pudo dar de alta. Intenta de nuevo.': "Couldn't register. Try again.",
  'Código del paciente': "Patient's code", 'Código que aparece bajo el QR': 'Code shown below the QR', 'Escribir código': 'Type code',
  'Apunta la cámara al código QR del paciente.': "Point the camera at the patient's QR code.",
  'No se pudo abrir la cámara. Usa "Escribir código".': 'Could not open the camera. Use "Type code".',
  'Código no válido o paciente no encontrado.': 'Invalid code or patient not found.',
  'Sin conexión. Revisa tu internet e intenta de nuevo.': 'No connection. Check your internet and try again.',

  // Sincronización y estados
  'Sin conexión': 'No connection', 'Sin conexión · {n} pendientes': 'No connection · {n} pending', '{n} pendientes de enviar': '{n} pending to send',
  'Sincronizando…': 'Syncing…', 'Sincronizado': 'Synced', 'Sincronizar ahora': 'Sync now', 'Todo sincronizado': 'All synced',
  'No hay registros pendientes de enviar.': 'No records pending to send.', 'Último error: {e}': 'Last error: {e}',
  'Guardado a las {h}': 'Saved at {h}', '{n} intento(s)': '{n} attempt(s)', 'Error al enviar': 'Error sending',
  'Sin conexión: guardado en el teléfono. Se enviará solo.': 'No connection: saved on the phone. It will be sent automatically.',
  'Sin conexión. Intenta más tarde.': 'No connection. Try again later.', 'No se pudo guardar. Intenta de nuevo.': "Couldn't save. Try again.",
  'No se pudo registrar. Intenta de nuevo.': "Couldn't record. Try again.", 'No hay información todavía': 'No information yet',
  'Cargando': 'Loading', 'No se pudo cargar': "Couldn't load", 'Intenta de nuevo en un momento.': 'Try again in a moment.',
  'Reintentar': 'Retry', 'Sin permisos': 'No permission', 'Tu cuenta no puede ver esta información.': 'Your account cannot see this information.',
  'Revisa tu internet. Lo que registres se guarda en el teléfono.': 'Check your internet. What you log is saved on the phone.',

  // Genéricos
  'Paso {n} de {t}': 'Step {n} of {t}', 'Siguiente': 'Next', 'Anterior': 'Back', 'Continuar': 'Continue', 'Cancelar': 'Cancel',

  // Integración con el backend (guía de conexión)
  'Acceso temporal del paciente': "Patient's temporary access", 'Contraseña temporal': 'Temporary password',
  'Anótalas y entrégalas al paciente: solo se muestran esta vez.': 'Write them down and give them to the patient: they are shown only this time.',
  'Adherencia (últimos 14 días)': 'Adherence (last 14 days)', 'Tomadas: {t} · Omitidas: {o}': 'Taken: {t} · Missed: {o}',
  'Sin medicamento: {n}': 'Without medication: {n}', 'Alergias que aparecen en el documento': 'Allergies found in the document',
  'Se pasarán a tu expediente para que el equipo de salud las revise.': 'They will be added to your record for the health team to review.',
  'Avisamos a tu equipo de salud y a tu cuidador.': 'We notified your health team and your caregiver.',
  'Buscar paciente': 'Search patient', 'Cambiar de paciente': 'Change patient', 'Contestar lo que falta': 'Answer what is missing',
  'Datos': 'Data', 'Demasiados intentos. Espera un momento.': 'Too many attempts. Wait a moment.',
  'Ej.: Naproxeno 250 mg, 1 tableta cada 8 horas por 5 días': 'E.g.: Naproxen 250 mg, 1 tablet every 8 hours for 5 days',
  'El número de arriba debe ser mayor que el de abajo.': 'The top number must be higher than the bottom one.',
  'El servicio no está disponible por ahora.': 'The service is not available right now.', 'Elige una opción.': 'Choose an option.',
  'En español: pide apoyo de un intérprete': 'In Spanish: ask an interpreter for help', 'Escribe el número.': 'Enter the number.',
  'Escribe lo que dice la receta': 'Type what the prescription says', 'Escribe los dos números de la presión.': 'Enter both blood pressure numbers.',
  'Esta alerta la atiende el equipo de salud. Si hay una emergencia, llama al 911 o acude a urgencias.':
      'The health team handles this alert. In an emergency, call 911 or go to the emergency room.',
  'Esta alerta ya estaba atendida.': 'This alert was already handled.', 'Esto ya estaba registrado.': 'This was already recorded.',
  'Falta:': 'Missing:', 'Faltan datos para evaluar tu registro': 'Some data is missing to evaluate your record',
  'Generado automáticamente: verifícalo con los datos.': 'Generated automatically: check it against the data.',
  'Hoy no hay preguntas en tu plan.': 'There are no questions in your plan today.',
  'La lectura automática no está disponible. Escribe la receta.': 'Automatic reading is not available. Type the prescription.',
  'Medicación': 'Medication', 'No hay conexión con el servidor. Revisa el cable o la red.': 'No connection to the server. Check the cable or the network.',
  'No me la tomé': "I didn't take it", 'No se encontró la información.': 'The information was not found.',
  'No se pudo entrar con la cuenta de demo.': "Couldn't sign in with the demo account.",
  'Por revisar: no lo encontramos en el catálogo. Tu equipo de salud lo revisará.': "To review: we didn't find it in the catalog. Your health team will review it.",
  'Prefiero escribir la receta': "I'd rather type the prescription", 'Registramos que no la tomaste.': "We recorded that you didn't take it.",
  'Resumen automático': 'Automatic summary', 'Resumen para consulta': 'Appointment summary', 'Revisa los datos marcados.': 'Check the highlighted fields.',
  'Sin medicamentos activos.': 'No active medications.', 'Sin resumen automático: se muestran solo los datos.': 'No automatic summary: only the data is shown.',
  'Tu médico aún no fija la meta de {v}': "Your doctor hasn't set the target for {v} yet", 'Versión {v}': 'Version {v}',
  'cada {h} h': 'every {h} h', '{n} alerta(s) abierta(s)': '{n} open alert(s)',
  '¿Cuánto marca tu glucosa?': 'What is your glucose reading?', '¿Cuánto marca tu presión?': 'What is your blood pressure?',
  '¿Cuánto marca tu temperatura?': 'What is your temperature?', '¿Cuánto pesas hoy?': 'How much do you weigh today?',
  '¿Cuántos latidos por minuto marca?': 'How many beats per minute?', '¿Por qué no la tomaste?': "Why didn't you take it?",
  '¿Tienes {s}?': 'Do you have {s}?', 'Arriba (sistólica)': 'Top (systolic)', 'Abajo (diastólica)': 'Bottom (diastolic)',
  'No': 'No', 'Leve': 'Mild', 'Moderado': 'Moderate', 'Fuerte': 'Strong', 'Muy fuerte': 'Very strong',
  'Se me olvidó': 'I forgot', 'No tengo el medicamento': "I don't have the medication", 'Me hizo sentir mal': 'It made me feel bad', 'Otro motivo': 'Other reason',
  'Todos': 'All', 'Rojo': 'Red', 'Ámbar': 'Amber', 'Verde': 'Green', 'Peso': 'Weight', 'Temperatura': 'Temperature', 'Frecuencia cardiaca': 'Heart rate',
  'oncologia': 'Oncology', 'Oncología': 'Oncology',
  // Síntomas (nombres para la pregunta "¿Tienes …?")
  'dolor de cabeza': 'a headache', 'zumbido de oídos': 'ringing in the ears', 'visión borrosa o luces': 'blurred vision or flashing lights',
  'hinchazón': 'swelling', 'sangrado': 'bleeding', 'fiebre': 'fever', 'salida de líquido': 'fluid leakage', 'contracciones': 'contractions',
  'convulsiones': 'seizures', 'ardor al orinar': 'burning when urinating', 'menos movimientos del bebé': 'fewer baby movements',
  'náusea': 'nausea', 'vómito': 'vomiting', 'diarrea': 'diarrhea', 'llagas en la boca': 'mouth sores', 'dolor': 'pain', 'cansancio': 'tiredness',
  'hormigueo o adormecimiento': 'tingling or numbness', 'falta de aire': 'shortness of breath', 'dolor de pecho': 'chest pain', 'mareo': 'dizziness',
  'temblor, sudor o debilidad (azúcar baja)': 'shaking, sweating or weakness (low sugar)',
  'Medicinas': 'Meds', 'Escanear': 'Scan',

  // Guía de integración (servidor, MEDMAP detallado, heridas)
  'Conectado al servidor': 'Connected to the server', 'Conectando…': 'Connecting…', 'El servidor no responde bien': 'The server is not responding correctly',
  'Sin conexión con el servidor': 'No connection to the server', 'Modo demo (sin servidor)': 'Demo mode (no server)', 'Cerrar': 'Close',
  'Leyendo tu receta… puede tardar hasta 25 segundos.': 'Reading your prescription… it may take up to 25 seconds.',
  'Hay {n} medicamento(s) que no se pudieron leer. Agrégalos a mano o toma otra foto.': "{n} medication(s) couldn't be read. Add them by hand or take another photo.",
  'Pendiente de validación clínica': 'Pending clinical validation', 'Esta receta ya se había guardado.': 'This prescription was already saved.',
  'Esta línea se leyó con dudas. Compárala con la foto.': 'This line was read with doubts. Compare it with the photo.', 'Ver la foto': 'View photo',
  'Dos lecturas no coinciden en {campo}. ¿Cuál dice la receta?': 'Two readings disagree on {campo}. Which one does the prescription say?',
  'Producto combinado:': 'Combination product:', 'Se guardará marcado para que tu equipo de salud lo revise.': 'It will be saved flagged for your health team to review.',
  'Revísalo: tu equipo de salud lo confirmará.': 'Review it: your health team will confirm it.', 'Indicaciones (p. ej. con alimentos)': 'Instructions (e.g. with food)',
  'Duración': 'Duration', 'Momento': 'Timing',
  'No encontramos este medicamento en el catálogo.': "We didn't find this medication in the catalog.",
  'Es un producto combinado que el sistema aún no reconoce.': "It's a combination product the system doesn't recognize yet.",
  'La sustancia la clasificó la IA; no está en el catálogo.': 'The substance was classified by AI; it is not in the catalog.',
  'La sustancia la dedujo la IA: confírmala.': 'The substance was inferred by AI: confirm it.', 'La lectura es dudosa: compárala con la foto.': 'The reading is doubtful: compare it with the photo.',
  'Seguimiento de heridas': 'Wound follow-up', 'Heridas en seguimiento': 'Wounds being followed', 'Herida': 'Wound', 'Registrar herida': 'Register wound',
  'Sin heridas en seguimiento': 'No wounds being followed', 'Registra una herida para darle seguimiento con fotos.': 'Register a wound to follow it with photos.',
  'Sin fotos todavía': 'No photos yet', 'Última foto: {f}': 'Last photo: {f}', 'Tipo de herida': 'Wound type', 'Zona del cuerpo': 'Body area', 'Lado': 'Side',
  'Descripción (opcional)': 'Description (optional)', 'Guardar': 'Save', 'Elige el tipo de herida y la zona del cuerpo.': 'Choose the wound type and body area.',
  'La IA describe y compara las fotos; no diagnostica. Todo queda para revisión del equipo de salud.': 'AI describes and compares the photos; it does not diagnose. Everything is left for the health team to review.',
  'Evolución': 'Progress', 'Fotos': 'Photos', 'Tamaño': 'Size', 'Estado': 'Status', 'Para revisión del equipo': 'For the team to review',
  'Descripción de la IA': 'AI description', 'Escala {n}: {p}': 'Scale {n}: {p}', 'confirmada': 'confirmed', 'Escala confirmada.': 'Scale confirmed.',
  'Foto de seguimiento': 'Follow-up photo', 'Foto enviada': 'Photo sent', 'Tamaño medido': 'Measured size', 'Comparación con la foto anterior': 'Comparison with the previous photo',
  'Para una buena foto': 'For a good photo', 'De frente y con buena luz.': 'From the front and with good light.',
  'La moneda en el mismo plano que la herida.': 'The coin on the same plane as the wound.', 'Toda la herida dentro del cuadro.': 'The whole wound inside the frame.',
  'Referencia de tamaño': 'Size reference', 'Revisa la foto y envíala.': 'Check the photo and send it.', 'Toca la moneda en la foto.': 'Tap the coin in the photo.',
  'Toca la tarjeta en la foto.': 'Tap the card in the photo.', 'Ahora toca la herida.': 'Now tap the wound.',
  'Listo. Puedes enviar la foto o tocar de nuevo para corregir.': 'Done. You can send the photo or tap again to correct.',
  'Enviar foto': 'Send photo', 'Enviando…': 'Sending…', 'No se pudo enviar la foto.': "Couldn't send the photo.", 'Sin conexión. La foto no se envió.': 'No connection. The photo was not sent.',
  'Foto de la herida': 'Wound photo',
  'Herida quirúrgica': 'Surgical wound', 'Úlcera por presión': 'Pressure ulcer', 'Pie diabético': 'Diabetic foot', 'Lesión de piel': 'Skin lesion',
  'Sitio de catéter': 'Catheter site', 'Otra': 'Other', 'Cabeza o cara': 'Head or face', 'Cuello': 'Neck', 'Tórax': 'Chest', 'Abdomen': 'Abdomen',
  'Espalda': 'Back', 'Sacro o glúteo': 'Sacrum or buttock', 'Brazo': 'Arm', 'Antebrazo': 'Forearm', 'Mano': 'Hand', 'Muslo': 'Thigh', 'Rodilla': 'Knee',
  'Pierna': 'Leg', 'Tobillo': 'Ankle', 'Talón': 'Heel', 'Dorso del pie': 'Top of the foot', 'Planta del pie': 'Sole of the foot', 'Dedos del pie': 'Toes',
  'Izquierdo': 'Left', 'Derecho': 'Right', 'Centro': 'Center', 'Moneda de 10 pesos': '10-peso coin', 'Tarjeta': 'Card', 'Ninguna': 'None',
  'Medicamento {n} de {t}': 'Medication {n} of {t}',
  'Marco legal: {m}': 'Legal framework: {m}',
  'Tu cuenta está desactivada. Pide ayuda a tu clínica.': 'Your account is disabled. Ask your clinic for help.',
};
